variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOC_SERV: "test_serv_02.dom_name"
  USER_NAME: "test"
  USER_PASSW: "test"

before_script:
  ## Install ssh-agent and sshpass if not already installed
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - 'which sshpass || ( apt-get update -y && apt-get install sshpass -y )'

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Create the SSH directory and give it the right permissions
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ## Use ssh-keyscan to scan the keys of your private server.
  - ssh-keyscan $DOC_SERV >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

docs_update:
  script:
    - sshpass -p "$USER_PASSW" ssh $USER_NAME@$DOC_SERV "bash -s" <  ./rebuild_docs.sh
  only:
    - develop